### ISSUE TITLE
ivy-native issue with the component variables in the templates

### ISSUE THREAD

**Issue by devhus** [angular/vscode-ng-language-service#1109]
After enabling the ivy-native feature my project got bugged where the templates(.html) couldn't recognize the component variables or methods at all nor showing any error when writing an undefined variable. the image below is when clicking on the ``go to definition`` option of the variable.

![image](https://user-images.githubusercontent.com/58523735/107858701-2d2ec680-6e3e-11eb-9c8a-719e35abe4ec.png)

**Additional context**

<pre>
Angular CLI: 11.2.0
Node: 14.15.1
OS: win32 x64

Angular: 11.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
</pre>

**UPDATES**
- updated my project to Angular 11, that didn't fix the issue.

**Comment by MatthewS2077** [comment]
I'm also having issues with the Ivy preview... it just doesn't work... created a new project `ng new` to test and I get `No config file for c:/temp/temp/src/app/app.component.html` in the output window for Angular Language Service.

**Comment by tonivj5** [comment]
Same issue than @MatthewS2077, but I'm on Linux. Language service with preview enabled doesn't work at all, same log with every component file

**Comment by admir86** [comment]
same error:

```
[Info  - 10:27:57] Angular language server process ID: 11620
[Info  - 10:27:57] Using typescript/lib/tsserverlibrary v4.1.5 from c:\Users\admir\.vscode\extensions\angular.ng-template-11.2.0\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:27:57] Using @angular/language-service/bundles/ivy v11.2.0 from c:\Users\admir\.vscode\extensions\angular.ng-template-11.2.0\node_modules\@angular\language-service\bundles\ivy.js
[Info  - 10:27:57] Log file: c:\Users\admir\AppData\Roaming\Code\logs\20210214T095505\exthost4\Angular.ng-template\nglangsvc.log
[Error - 10:28:15] No config file for c:/Users/admir/Azure-DevOps/test-ng-lang-service/ng-app/src/app/app.component.html
[Error - 10:28:33] No config file for c:/Users/admir/Azure-DevOps/test-ng-lang-service/ng-app/src/app/app.component.html
[Error - 10:28:41] No config file for c:/Users/admir/Azure-DevOps/test-ng-lang-service/ng-app/src/app/app.component.html
[Info  - 10:28:50] Enabling Ivy language service for c:/Users/admir/Azure-DevOps/test-ng-lang-service/ng-app/tsconfig.json.
[Error - 10:28:52] No config file for c:/Users/admir/Azure-DevOps/test-ng-lang-service/ng-app/src/app/app.component.html
```

```
Angular CLI: 11.2.0
Node: 12.16.2
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
```

**Comment by MatthewS2077** [comment]
So looking forward to this being fixed and being able to apply rename refactoring to templates 💪

**Comment by ivanwonder** [comment]
I downgrade the version of ts to 4.1.3 in the extensions. It works again. Maybe this is the problem.
https://github.com/angular/vscode-ng-language-service/blob/18291b87d82ef848521236ddcfc9082d4f65a6b5/client/src/client.ts#L277

**Comment by 255kb** [comment]
For me extension in v11.1.3 is working well. Updating to 11.2.0 breaks everything

**Comment by jtsom** [comment]
Am seeing the same issue in the html file, with errors in the console every time I hover something:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/13488/107956915-e04a0d80-6f6d-11eb-9d26-21e59b0f32e9.png">


Also seeing double when hovering over variables, etc. in the component file:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/13488/107956984-f657ce00-6f6d-11eb-8dc2-b2bc37632ad4.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/13488/107957006-ff489f80-6f6d-11eb-88fc-ec35e5bcb92e.png">

... turning Ivy off.

**Comment by AaronDovTurkel** [comment]
How do you turn off Ivy? tried downgrading the extension but still having the issue described...

**Comment by 255kb** [comment]
@AaronDovTurkel add `"angular.experimental-ivy": false` in your VSCode settings

**Comment by ivanwonder** [comment]
https://github.com/microsoft/TypeScript/pull/42713
I think this pr break the plugin. `@angular/language-service/bundles/ivy` is disabled.

**Comment by yiqu** [comment]
Turning it off. Everything is doubled and in template it doesnt actually work.

**Comment by Eventyret** [comment]
Just to add to @jtsom I had the same issue now, turned ivy off with `"angular.experimental-ivy": false` and it works like a charm. 
Thanks for the hard work people are doing on this btw.

**Comment by kyliau** [comment]
Hello everyone, this issue has been fixed in v11.2.1, and it has been released to the vscode marketplace.
We are sorry for the inconvenience.
This is a mistake that's totally preventable, and as a result I've written a [post-mortem](https://github.com/angular/vscode-ng-language-service/issues/1120) to explain what happened, and what we will do to ensure a higher engineering standard to prevent this from happening in the future.
Please let us know if you have any suggestions / feedback.

**Comment by MatthewS2077** [comment]
Fixed, and thanks!  👍
Is, rename refactoring meant to work for templates? It doesn't seem too... 🤔

**Comment by kunajs** [comment]
Hi, seems that duplicities still occur within "Find all references" results, even with v11.2.1 😕

**Comment by kyliau** [comment]
> Hi, seems that duplicities still occur within "Find all references" results, even with v11.2.1 😕

@kunaja could you please open a new issue and attach a repro / screenshot so that we can take a closer look? Thank you.

**Comment by kunajs** [comment]
> > Hi, seems that duplicities still occur within "Find all references" results, even with v11.2.1 😕
> 
> @kunajs could you please open a new issue and attach a repro / screenshot so that we can take a closer look? Thank you.

https://github.com/angular/vscode-ng-language-service/issues/1124
