### ISSUE TITLE
Output Window gets opened when I type

### ISSUE THREAD

**Issue by bogacg** [angular/vscode-ng-language-service#128]
Output window gets opened any time I type some code and shows language service output.

When I close it doesn't have permanent effect, it gets opened again when I type.

I can't see any settings in the plugin. What shall I do? I don't want Output window open.

**Comment by cvanlaw** [comment]
This is happening for me as well, but didn't start until I updated to VS Code version 1.14.1 this morning.

VSCode version: 1.14.1
Angular Language Service Extension version: 0.1.4

**Comment by mtycholaz** [comment]
Temporary fix right now is to leave your Output window open, but reduce the size to the minimum.

**Comment by cvanlaw** [comment]
I downgraded to VS Code 1.14.0 for now and that resolved it for me. Before I downgraded, I also noticed that autocomplete had each suggestion in triplicate - not sure if that's a VS Code issue or a plugin issue.

**Comment by DBosley** [comment]
This issue is preventing me from updating vscode

**Comment by RaviSankarRao** [comment]
These updates are becoming nightmare day by day :(

**Comment by ttugates** [comment]
This window behavior is very distracting.  I particularly like the terminal to always show.  Am disabling until resolved.

**Comment by DavidTheProgrammer** [comment]
@cvanlaw Where can I find the 1.14.0 Download? I'm tired of the minimal size window workaround

**Comment by lemoinem** [comment]
You should stop grabbing focus. Pleaser refer to https://github.com/Microsoft/vscode/issues/31474#event-1185523706 as to how to do it.

**Comment by DavidTheProgrammer** [comment]
@lemoinem I can't see anything in there about stopping this action. They just talk about how their API allows applications to grab focus and not how to prevent it

**Comment by DBosley** [comment]
I can't seem to reproduce this issue in the latest vscode. But I can't seem to get the language service features to work at all anymore. I see messages in the output log, but it's not pulling my focus. It's also not showing any hover help for things like *ngIf and *ngFor which I know it showed before.

**Comment by DBosley** [comment]
@lemoinem I've been looking through the code of this project. I can't find any references to that `show()` method you're linking.

**Comment by nickprivalov** [comment]
Please get this fixed soon.  Removing focus from terminal is becoming detrimental to work.

**Comment by DBosley** [comment]
@nickprivalov are you experiencing this with the latest version of VSCode? I'm trying to solve this issue myself, but I can't reproduce it anymore.

**Comment by nickprivalov** [comment]
Just got the update, can confirm your issues with *ngIf and *ngFor directives not appearing.  Can also confirm that the Language Service doesn't pop up like before, but have only been using the new version for barely 10 minutes.

**Comment by DavidTheProgrammer** [comment]
What version is the "new version"? 1.14.2? Because it's happening to me with this version.

**Comment by nickprivalov** [comment]
Yup, disregard what I said it still occurs.

**Comment by DBosley** [comment]
@nickprivalov and @DavidTheProgrammer do either of you have a repo I could pull down that has the issue so I could repro it locally? How long did you have to use VSCode before it happened? Are there any errors in the output window?

**Comment by bogacg** [comment]
I don't see any problem now, seems to be fixed. Thanks

**Comment by lemoinem** [comment]
@DavidTheProgrammer @DBosley 
I still have the issue on the last (1.14.2) version of VScode, it starts as soon as I open VSCode.

I don't know about the `show` method, but this is what has been answered to me when I reported the issue to VSCode team. If the issue is with VSCode's API or own behavior, I suggest you contact them directly. It will most probably be more efficient than having me or other end-users playing ping-pong between the teams.

**Comment by DBosley** [comment]
I just submitted a PR for this project with updated deps. I've been using the extension built locally with these updates for a week or two now and it all seems to be running smoothly.

Just gotta wait on @chuckjaz to give it the thumbs up.

**Comment by DBosley** [comment]
I was able to see this happen in person today, finally. It seems to switch to the output window when there's an error. This is the error that happened when I saw it:
```
[Error - 3:08:57 PM] SERVER ERROR: Cannot read property 'identifier' of null
TypeError: Cannot read property 'identifier' of null
    at tokenReference (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:18980:14)
    at Object.visitReference (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50335:62)
    at ReferenceAst.visit (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:17198:24)
    at locateSymbol (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50314:22)
    at getHover (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50589:18)
    at LanguageServiceImpl.getHoverAt (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50662:20)
    at C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2705:68
    at time (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2687:22)
    at Object.getHoverAt (C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2705:20)
    at C:\Users\UserName\.vscode\extensions\Angular.ng-template-0.1.4\server\server.js:171:30
[Error - 3:08:57 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'identifier' of null
  Code: -32603
```

Posting here to keep track of it so I can look into it later

**Comment by DavidTheProgrammer** [comment]
That's exactly what pops up! And yes, I've noticed that it pops up when you hover over a directive or something in the template with a red underline ....

**Comment by DBosley** [comment]
@DavidTheProgrammer I can reproduce it! It seems to trigger when hovering over template variables. (e.g. #descriptionInput on an input in my case).

I'll verify that the dependency updates I created a PR for resolves it, if not I have a few ideas on how to fix it.

**Comment by frederikschubert** [comment]
@DBosley I tested it with your PR and I do not get this error anymore. Also my other [issue](https://github.com/angular/vscode-ng-language-service/issues/121) is fixed with your dep update.

**Comment by DBosley** [comment]
I found the issue in the angular project that relates to this:
https://github.com/angular/angular/issues/17972
It seems to have already been fixed by @chuckjaz. So my PR should close this bug.

**Comment by DBosley** [comment]
PR #138 should catch and handle all errors from the @angular/language-service when getting language-service data.

**Comment by bogacg** [comment]
When I try to update this plug-in, I still get v. 0.1.4 on store.
I had to download manually `vsix` file to get latest.

**Comment by chuckjaz** [comment]
I have not published 0.1.5 because it is broken. It requires `minimist` be loadable. I should have a version without this requirement on Wed or Thurs.

**Comment by ShiftySituation** [comment]
For resolution to the issue, please take a look at the `OutputChannel` interface at [https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3325](github vscode).  There is a `show(preserveFocus?: boolean): void;` where if preserveFocus is true, it doesn't take focus.

**Comment by chuckjaz** [comment]
My code does not call that method at all (https://github.com/angular/vscode-ng-language-service/blob/master/client/src/extension.ts). This is call happens in the client library I am using which is provided by the vscode team.

**Comment by DBosley** [comment]
@ShiftySituation The majority of "auto-open" issues should be resolved after the next release. Feel free to download the visx file from the releases tab if you want to get it early.

**Comment by Alexintosh** [comment]
Very annoying, I hope it will be released a fix asap.

**Comment by idchlife** [comment]
Actually this is not the only issue with this plugin. I think VSCode should generally add option to disable popping out - we should just see like alert at the bottom, but not popping up panel

**Comment by murilobd** [comment]
This is really really annoying indeed! =/

**Comment by AndrewHuffman** [comment]
I find this infuriating, has the fixed not yet been released?

**Comment by kmaida** [comment]
This just started happening to me. Very aggravating, since I use the Terminal heavily, and when I have that open it pops open the output window and changes to it constantly.

**Comment by AnalyzePlatypus** [comment]
This is happening to me as well. The output window snaps open every few seconds with normal output. Killing VSCode and restarting helps for a few minutes.

**Comment by Mastermindzh** [comment]
Am also experiencing this bug, will have to disable the plugin I guess 😢

**Comment by Brampage** [comment]
@idchlife This is not true isidorn comments in this thread the following:

```
This is an issue with the extension, our current api allows extensions to say preserveFocus: true
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3325

Please file this against the angular2 extension
```

**Comment by Brampage** [comment]
This is so annoying I think I will stop using this great extension if this is not fixed.

**Comment by roopkt** [comment]
I am also facing this even though I select terminal as my tab and minimize the entire integrated terminal Angular Language Service Output still pops up while working on any file and disturbs.

**Comment by ShiftySituation** [comment]
[My proposal to remedy this annoyance across the board](https://github.com/Microsoft/vscode/issues/36844)

**Comment by kobekoto** [comment]
+1 great VScode extension but output is super annoying and distracting

**Comment by CalvinDale** [comment]
Ditto, irksome. I sure wish that it was fixed. I've encountered this issue in previous builds a few months back.

**Comment by joe307bad** [comment]
This is really frustrating, anyone have any idea how to prevent this from happening?

**Comment by CalvinDale** [comment]
@joe307bad Try shutting down all instances of VS Code and then re-launching. I've found that occasionally (but not consistently) this works.

**Comment by Stranger** [comment]
How is this not fixed yet?

**Comment by RogierKonings** [comment]
I will be disabling the angular language service until this is fixed

**Comment by Alexintosh** [comment]
I will migrate my app to React  until this is fixed

**Comment by idchlife** [comment]
@Alexintosh dear god, because of opening panel you will migrate your app to another framework?

**Comment by luizhsalazar** [comment]
really annoying! any workaround to stop this?

**Comment by verysimplenick** [comment]
@DBosley maybe need reopen?

**Comment by ewaschen** [comment]
Happens whenever I open or save a file.   Started since Angular Language Service was installed.
