### ISSUE TITLE
Fail to detect older Angular projects < v9

### ISSUE THREAD

**Issue by nedex** [angular/vscode-ng-language-service#1350]
# 🐞 bug report

### Is this a regression?

Kinda, since the extension will not correctly detect the project's Angular version and set the default setting to a proper value.
A lot of developers will have this issue so that's the main reason of this issue report.

_Note:_ I'm actually working on a project whose Angular version can't be updated at the moment.

### Description
Latest extension release states:
<pre>Older projects will keep using View Engine language service.</pre>
By the way, it doesn't seem to work, and it will raise the following error for older Angular projects:
<pre><code>Failed to resolve ngcc [...] Language service will remain disabled.</code></pre>

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Open an Angular < v9 project (not sure about the version, personally I'm on v7)
2. The `Failed to resolve ngcc` error will be displayed and the extension will not work

**Expected behavior**

The extension should be able to detect a pre-ivy project and automatically enable the `angular.view-engine` setting.

## "Temporary fix"

Set the `angular.view-engine` workspace setting to `true`.

### **Logs**

Popup displayed:
<pre>Angular extension might not work correctly because ngcc operation failed.
Try to invoke ngcc manually by running 'npm/yarn run ngcc'. Please see the extension output for more information.</pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 7.1.4
Node: 10.16.0
OS: win32 x64
Angular: 7.1.4</code></pre>

Extension Version:
<pre><code>v12.0.0</code></pre>

VSCode Version:
<pre><code>v1.56.1</code></pre>

Operating System:
<pre><code>Windows 10 Version 10.0.19042 Build 19042</code></pre>

**Comment by niladrisen6** [comment]
project compilation issue. failed to resolve ngcc.
Angular CLI: 8.3.29
Node: 14.15.5

**Comment by Dovernh** [comment]
I am also receiving this issue, report several modules:

export declare class NzRateModule {
Appears in the NgModule.exports of NgZorroAntdModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (ng-zorro-antd/slider) which declares NzSliderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

This likely means that the library (ng-zorro-antd/table) which declares NzTableModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Error: Error on worker #4: RangeError: Maximum call stack size exceeded
    Language service will remain disabled.

**Comment by kyliau** [comment]
@nedex Could you please provide the logs? Also please double check your vscode config to make sure Ivy is turned off.
To get the logs, please run the vscode command `Open Angular Server log`.
The fact that you're seeing the error message `Fail to resolve ngcc...` means that the server is already spawned in Ivy mode, which should not happen. The client is responsible for detecting the Angular version of your project, and spawn the right server. We need more information to understand what's going on. Thank you!

**Comment by nedex** [comment]
> @nedex Could you please provide the logs?

I will provide the logs ASAP.

> Also please double check your vscode config to make sure Ivy is turned off.

I also tried to add a `angularCompilerOptions` section with `enableIvy` as the only value set to `false`, but the behaviour didn't change.

> The client is responsible for detecting the Angular version of your project, and spawn the right server.

I saw [some lines of code of the extension](https://github.com/angular/vscode-ng-language-service/blob/9dba839b3a8794e5e84567cf0297c1284963c0a2/client/src/client.ts#L451), and the extension actually checks if the project's Angular version is < 9, so that's why I wrote this issue.
Otherwise, if the developer is responsible for setting the right settings, expect a lot of them to have my same issue since I didn't modify any settings and this error popped out from nowhere.
At least this will be useful to them to fix the problem.


Please let me know if I can do something for you in the meanwhile.
Thanks!

**Comment by kyliau** [comment]
Yeah, our goal is to make the extension detect the right Angular version, and pick the language service accordingly. 
There should be no manual configuration needed on the user's side.

Meanwhile, if your project is using Angular < v9, you can explicitly tell the extension to use View Engine language service by checking the View Engine option in vscode **Workspace** settings (not User, as that'll affect all projects):

<img width="2036" alt="Screen Shot 2021-05-13 at 9 49 28 AM" src="https://user-images.githubusercontent.com/2941178/118158461-a5bb0a00-b3d0-11eb-9439-a53cacf6e5ee.png">

**Comment by nikesh9220** [comment]
In my Project, we are also facing the same issue after upgrading it to version 12.
We are using Angular 8.2

We have two temporary solutions until this Bug will fix.
1. Downgrade it to 11.2.14 and remove the node modules folder and then hit npm i then it will work
2. If you want to use Version 12 then follow the @kyliau suggestion (Check on Use Legacy View Engine)

![image](https://user-images.githubusercontent.com/33998764/118237283-c9578080-b4b4-11eb-9c87-a9aefdc31994.png)

**Comment by micaminoff** [comment]
For people arriving here wondering why their projects won't build, try deleting your project's `node_modules` folder and doing `npm install`. Ivy creates a bunch of files that cause issues with legacy projects.

**Comment by vixtorocha** [comment]
I'm also having this issue with `v12.0.0` of the extension. My project uses Angular `v7.2.16`.

**Comment by isener** [comment]
In VSCode -> Workspace Settings -> Search View Engine -> Check checkbox Use legacy View Engine … -> clean node_modules -> run npm install

**Comment by kyliau** [comment]
For anyone who's experiencing this, _please_ send us the logs from the server to help us debug this issue. 
The extension is supposed to detect the Angular version of your project.
In this case, it looks like the detection logic fails for certain projects, and we need the logs to understand what's going on.

**Comment by ivanwonder** [comment]
@kyliau I think the problem is the default value.
https://github.com/angular/vscode-ng-language-service/blob/ee741f8e90accd67326aff1c74d61e8181c7e473/package.json#L87
https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration
Looks like the vscode treats it as `false` if I remove the default value.
```ts
const viewEngine: boolean = config.get('angular.view-engine') || !allProjectsSupportIvy();
```

**Comment by nedex** [comment]
@kyliau I quickly made a new project using the following command:

`npx -p @angular/cli@v7-lts ng new angular7`

and the bug is still there.

You may find the project here, with the requested `nglangsvc.log` file in the main directory
[https://github.com/nedex/angular7](https://github.com/nedex/angular7)

Thank you.

**Comment by kyliau** [comment]
Thanks @ivanwonder for fixing the bug! We've published v12.0.1 with the fix, my sincere apologies for breaking users on older Angular versions.

**Comment by gnans** [comment]
@kyliau This issue is not yet resolved. I am using v12.0.2 and it is still happening

**Comment by ivanwonder** [comment]
https://github.com/angular/vscode-ng-language-service/blob/fa36c291fb9afd15bcd84686d770c207893254f1/client/src/client.ts#L474-L483
I think the ALS extension resolves the `@angular/core` from the root path of workspace. Maybe your angular project is a subproject under the workspace. @gnans
