### ISSUE TITLE
Angular LS sometimes breaks with solution-style project configuration (used by NX) 

### ISSUE THREAD

**Issue by LcsGa** [angular/vscode-ng-language-service#1444]
### Description

I have an Nx project, using angular and nestjs. In this project, I'm using primeng components. Usually, when I simply have my angular project, outside of an nx project (this is my first time with nx) the extension works pretty well (vscode).
Right now in that project, I encounter some errors in my HTML components, on primeng components (90% of the time) and autocompletion won't work anymore for these (rarely and randomly it works well though, without me doing anything special). This only is an issue caused by this extension, in an nx environment. The project works and compiles pretty well though and this issue just shows errors that are not right, eg:
'p-tieredMenu' is not a known element:
1. If 'p-tieredMenu' is an Angular component, then verify that it is part of this module.
2. If 'p-tieredMenu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ngtsc(-998001)
(Even if I add the CUSTOM_ELEMENTS_SCHEMA, the problem remains)

That issue is so annoying!!

## Bug Type
Wrong errors highlighted in xxxx.component.html files, on primeng components (never tried on other external components)

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create an nx project with angular and nest
2. Add primeng to that project
3. use primeng components in HTML templates (import them in the right modules)
4. You may need to reload vscdoe to make this "errors" happen (unfortunately, this is a little random)

**Expected behavior**
No fake errors highlighted and autocompletion working for these external components

### **Screenshots**
![image](https://user-images.githubusercontent.com/58547290/125213544-d4f7d580-e2b2-11eb-81ea-16f9e5a99569.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

12.1.1

</code></pre>

Extension Version:
<pre><code>

12.1.1

</code></pre>

VSCode Version:
<pre><code>

1.58.0

</code></pre>

Operating System:
<pre><code>

Ubuntu 20.04.2 LTS

</code></pre>

**Anything else relevant?**
I tried removing all other extensions except for angular language service but the problem remains and I also tried to reload the angular language server more than once but it never fixed anything

**Comment by atscott** [comment]
Hi @LcsGa, could you provide a project that this issue can be reproduced with? I followed the steps that you listed but wasn't able to reproduce the issue.

**Comment by LcsGa** [comment]
Hi @atscott ! Sure, you can clone the project on which I encounter the issue!
https://github.com/LcsGa/GarciaLucas_7_08072021

**Comment by atscott** [comment]
@LcsGa Thanks. We were able to get it to reproduce a couple times and found that the language service might be having trouble with the solution style tsconfig. When we got the error, the compiler had chosen the `tsconfig.spec.json` as the file's project which clearly would not work.

**Comment by LcsGa** [comment]
Oh okay! Now I understand why I have this issue! I also thought that it was due to the numerous config files that would "disturb" the extension! What can I do about it then? Isn't it possible to specific a default tsconfig?

**Comment by m0rtyn** [comment]
Same problem: NX with several tsconfigs + vscode + NG12. It doesn't always show up, but it's annoying.

**Comment by atscott** [comment]
This is fixed by #1447 and will be included in this week's release (likely tomorrow, but could be later)

**Comment by davidrock** [comment]
@atscott unfortunately this problem is still happening. A very similar project, but instead of _PRIMENG_ components, it is breaking my own components created with StencilJS inside an NX workspace. I don't know whether it is the same kind of problem or not. The project itself is running without any error.

Restarting the **Angular Language Service** seems to fix for some time, but then after some time, those errors start again.

**Comment by atscott** [comment]
@davidrock - Could you provide a repository that this issue can be reproduced in? I don't know how this would happen sporadically. The previous issue was because the language service could be enabled in a different order than what was listed in the `tsconfig`, but that shouldn't happen anymore.

**Comment by LcsGa** [comment]
Actually, I also still encounter this issue sometimes (but less often than before) but at list, when it happens, I just restart the angular language service with the provided command and it works! (Therefore sometimes I have to do it multiple times in a row for it to work)

**Comment by m0rtyn** [comment]
> Actually, I also still encounter this issue sometimes (but less often than before) but at list, when it happens, I just restart the angular language service like David said! (Therefore sometimes I have to do it multiple times in a row for it to work)

Same case, but good enough.
