### ISSUE TITLE
Angular Language Server needs to be restarted very often

### ISSUE THREAD

**Issue by TheColorRed** [angular/vscode-ng-language-service#1616]
# 🐞 bug report

### Is this a regression?

 No, this has been happening for a while

### Description

 
Every so often I need to run `Angular: Restart Angular Language server` because eventually intellisense stops working, goto component stops working (<kbd>CTRL+Click</kbd> or <kbd>F12</kbd>). However, **Go to component** still displays above the first line, and got to template/styles still works via <kbd>CTRL+Click</kbd> or <kbd>F12</kbd>. This just seems to stop working within templates after awhile.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

**Expected behavior**

The plugin should not stop working

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

See Attachment
</code></pre>
[Angular Language Server.txt](https://github.com/angular/vscode-ng-language-service/files/8287563/Angular.Language.Server.txt)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.2.5
rxjs                            7.5.5
typescript                      4.5.5
</code></pre>

Extension Version:
<pre><code>

v13.3.0
</code></pre>

VSCode Version:
<pre><code>

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
</code></pre>

Operating System:
<pre><code>

Windows_NT x64 10.0.19044
</code></pre>

Extension options:
<pre><code>

Defaults
</code></pre>

**Anything else relevant?**

**Comment by Proantagonist** [comment]
I have this exact same issue and it's been a thing for a very long time. Very frustrating and adds a lot of friction to development.

**Comment by daniol** [comment]
Same problem here. It happens to me every time a .js file is replaced externally.

**Comment by vjp-ignacioDJ** [comment]
Me pasa lo mismo y es muy molesto ojala que lo solucionen

**Comment by kiwidude68** [comment]
Yes unfortunately this extension is pretty much unusable nowadays for those of us using Angular 13 from my experience. In the past the only way this extension didn't constantly fall over for me was to tick the "Use legacy View Engine language service" option. Which apparently isn't an option that works with Angular 13, so instead we are back to a constant sea of red when looking at our .html files in between repeatedly doing a restart of the addin. Extremely frustrating, I would uninstall it completely but for that fact that when it does briefly work it can add some value.

Fingers crossed one of the devs who knows wtf is going on can fix it...

**Comment by daniol** [comment]
Related with #1169 and angular/angular#41032 (the last one theoretically fixed but obviously the issue does not disappear)

**Comment by atscott** [comment]
Does anyone experiencing this issue have a reproduction? Without one, there can't be any progress made and finding the root cause and solution.

**Comment by atscott** [comment]
@kiwidude68 issues with nx projects are covered in #876 and #1581. If it's the case that other projects experiencing this problem are using project references/nx then this issue should be closed as a duplicate.

**Comment by kiwidude68** [comment]
@atscott - very interesting, so perhaps it is an Nx + ALS triggered issue rather than an ALS issue alone. I only have one Angular project I work on being this one so have nothing else to compare it to :). 

Neither of those issues seem to be identical to my particular problem though perhaps they all come from the same root cause. I guess the worrying thing is that if it is from #876 which has been open for so long. Also as I mentioned above there was a "workaround" prior to Angular 13 of using that "Use legacy View Engine service" option - with that enabled and Angular 11/12 I had no issues with ALS at all. Of course I have no idea whether that actually means anything...

As to closing this issue, the original poster above appeared to not have Nx. I jumped on this thread because it was the most recent "frequent restart" thread I spotted.

One thing from those linked issues I learnt was how to find the logs for ALS/enable logging. I found two errors - firstly this is the one that appeared at the exact moment the html broke before my eyes:
`[Error - 5:50:22 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Language service does not have a program!
  Code: -32603 `

and this one also appears several times in the log file, though not frequent enough to coincide with this issue:

```[Info  - 4:50:17 PM] Enabling Ivy language service for d:/Git/prime-portal/prime-portal-ui/libs/portal/feature-reports/tsconfig.lib.json.
(node:116920) UnhandledPromiseRejectionWarning: Error: Language service does not have a program!
    at Object.getProgram (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\node_modules\@angular\language-service\bundles\language-service.js:44902:27)
    at CompilerFactory.getOrCreate (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\node_modules\@angular\language-service\bundles\language-service.js:41713:50)
    at LanguageService.withCompilerAndPerfTracing (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\node_modules\@angular\language-service\bundles\language-service.js:44817:51)
    at LanguageService.getCompilerOptionsDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\node_modules\@angular\language-service\bundles\language-service.js:44830:25)
    at Object.getCompilerOptionsDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\node_modules\@angular\language-service\bundles\language-service.js:45088:38)
    at Session.handleCompilerOptionsDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\server\index.js:4035:52)
    at Session.enableLanguageServiceForProject (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\server\index.js:4008:14)
    at Session.runNgcc (c:\Users\xxx\.vscode\extensions\angular.ng-template-13.3.0\server\index.js:4602:16)```

Whether that helps anyone I have no idea...

**Comment by atscott** [comment]
Closing as fixed by https://github.com/angular/vscode-ng-language-service/commit/fbc9e2b4b1de0a3944346d16a7a2d0270c451549. See https://github.com/angular/vscode-ng-language-service/issues/1616#issuecomment-1082167253

**Comment by daniol** [comment]
The beta release v14.0.0-next.0 does not solve the issue for me, even if I disable "ngcc".
@atscott Please reopen this issue!

Steps:

1. Open Angular 13 Project
2. Start development server (`ng serve`)
3. Replace a file externally, with a copy that just adds a line of code (emulates an external code generation tool)
4. "ngtsc" non-sense errors are displayed

![errors](https://user-images.githubusercontent.com/196808/161693956-49575c1b-1f0f-43d8-b500-9cb6e7662418.png)

I turned debug level to "verbose" and I see this on the "nglangsvc.log" (I replaced common_pb.d.ts externally): 

> Info 772  [8:32:8.69] A plugin threw an exception in getExternalFiles: Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
Info 773  [8:32:8.90] Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
    at c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:164982:30
    at Object.map (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:652:29)
    at ConfiguredProject.Project.getScriptInfos (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:164980:27)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\bundles\language-service.js:45477:42)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\index.js:27:149)
    at c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:164876:46
    at Object.flatMap (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:716:25)
    at ConfiguredProject.Project.getExternalFiles (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:164872:35)
    at ProjectService.reloadFileNamesOfConfiguredProject (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:168109:86)
    at ConfiguredProject.updateGraph (c:\_MyProjects\connect-emission\frontend\node_modules\typescript\lib\tsserverlibrary.js:166141:54)

@atscott Is there any way you can analyze the bug? My profile shows my email address, so maybe you can take a look remotely?

**Comment by kiwidude68** [comment]
Just to backup @daniol - nothing is fixed for me either with the preview. I'm still having to restart the extension constantly. In my case (like others) it appears to be a combination with Nx that is triggering the behavior, but I suspect this is falling into the cracks between the two project teams of who is going to try to fix it. I simply don't have the Angular knowledge to contribute to the solution.

**Comment by atscott** [comment]
@daniol Thanks for the reproduction, that's really helpful. It looks like your case is different from the one described here. Please open a new issue for this with the same information.

**Comment by atscott** [comment]
@daniol Actually it looks likely that yours is a duplicate/same root cause of #1387.

**Comment by atscott** [comment]
@kiwidude68 Do you have any additional information about how to reproduce your issue? I went back to read all your comments in this thread but didn't see any description of how to reproduce the issue or verbose logs that might help pin down what's happening.

**Comment by kiwidude68** [comment]
@atscott I sort of offered to try to put together a repo case earlier in the thread but we kind of got a little sidetracked with the other jiras you linked in this thread that had mentioned issues combined with Nx. As they were still open so I took that to mean my effort might be fruitless if its just an accepted "broken" combination. However if it is just that no-one has built a repro case for you and that it would be looked into if I did then I can take a few hours to try to put something together.

**Comment by kiwidude68** [comment]
@atscott - sorry I missed that bit in your earlier post about it being a new option that has to manually be disabled in the preview release - muppet. I just now found it and ticked it. Let me see if indeed that fixes things before I try building a repro - your confidence has me wanting to give that a spin first.

Please excuse my ignorance here on the whole ngcc thing here but is there a numpties guide in english somewhere of exactly what if any changes I now need to make after ticking that option in the ALS extension? At the moment I can see a postinstall script in package.json which does this:
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",

Do I now have to do anything else for whenever I normally do the following tasks?
- run our app locally using ng serve
- upgrade dependencies using npm install
- build our releases using ng build

Our tsconfig.json has all been built since a year ago with Angular 11 (now 13 of course) with latest Nx, our application and our libraries should all be Ivy enabled, however I know that some of the third party libraries we depend on like ag-grid are not. Sorry if this is a dumb question to you but I'm a backend developer who was forced to dive into Angular for this project and the dark arts of the build pipeline and convoluted myriad of config files (with all the extra Nx layers on top) are not at all intuitive...

**Comment by atscott** [comment]
@kiwidude68 No worries. It looks like you won't need to update your workflow at all. `ng serve` should take care of rerunning `ngcc` at the necessary times.

**Comment by atscott** [comment]
@daniol I did some more investigation into the information you provided and I'm not sure this is an issue with the Angular extension. The call stack is all in the TS server code, specifically `getExternalFiles`. This is called when the program is updated due to a file change. Our extension _does_ trigger this update request and if it fails, the effect would be that we can't compile the project and result in the errors you're seeing.

TS server's `getExternalFiles` implementation calls each plugin's `getExternalFiles` function if implemented. The Angular language service extension no longer implements this method (more background here: https://github.com/angular/vscode-ng-language-service/issues/473) so the error could be caused by another extension. 

Can you try disabling all other plugins in VSCode to see if this makes the failure go away? If that doesn't resolve the issue, can you provide a project to reproduce this with? Your reproduction steps indicate it should be simple to do with an `ng new` project but I wasn't able to (possibly because I don't have whatever plugin is installed which is causing the breakage).

**Comment by Proantagonist** [comment]
Just spent some time testing and here's what I've found. 

I have three repo's in which I can reliably cause the extension to crash. However, before I go through that, I hadn't realized (ignorance on my part) that there was in fact another check box in the settings for the ALS extension. I checked it and for me it *seems* to have fixed the problem. The extension still crashes but recovers and no longer paints the entire screen with red underlines that only go away with a VS reload. So just to be thorough:

1) I've ticked the new setting in the ALS extension settings:

![image](https://user-images.githubusercontent.com/3969818/161874334-3f29283b-9d8d-4872-a3e6-394a052b628c.png)

![image](https://user-images.githubusercontent.com/3969818/161874348-dd9d0cc2-ce42-482f-abcb-61117174754e.png)

2) Reload VSC after ticking.

3) Start the app serve in PowerShell under Windows Terminal, not the integrated terminal in VSC. Shouldn't make a difference, but mentioning it just in case.

With that alone the problem appears to be fixed in three repos (all nx workspaces) that I've tested.

I can only share two of the three repos affected, if it's in any way helpful for debugging purposes for those that still might be having issues. 

### Repo 1

URL : https://github.com/Supreme-Gaming/SupremeGaming
Branch: `website-updates-1`

1) Open `libs\ui\src\lib\modules\player-tribe-explorer\components\player-details\player-details.component.html`
2) Open `libs\ui\src\lib\modules\player-tribe-explorer\components\player-details\player-details.component.scss`
3) Serve the app `nx run supremegaming-angular:serve` (Serving is not strictly necessary. Extension will still crash without serving.)
4) In the component style sheet, add `display: block` in the `:host` selector.
5) Save style changes and wait for angular compile
6) Template should light up red

![image](https://user-images.githubusercontent.com/3969818/161876517-c8ff78c9-a39d-4a66-b9e1-66d7faf11ed4.png)


### Repo 2

URL : https://github.com/TamuGeoInnovation/Tamu.GeoInnovation.js.monorepo
Branch: `development`

1) Open `libs\aggiemap\ngx\ui\desktop\src\lib\modules\sidebar\components\sidebar-trip-planner\sidebar-trip-planner.component.html`
2) Open `libs\aggiemap\ngx\ui\desktop\src\lib\modules\sidebar\components\sidebar-trip-planner\sidebar-trip-planner.component.scss`
3) Serve the app `nx run aggiemap-angular:serve` (Serving is not strictly necessary. Extension will still crash without serving.)
4) In the component style sheet, add:

 ```css 
:host{
  display: inherit;
}
```
5) Save style changes and wait for angular compile
6) Template should light up red

![image](https://user-images.githubusercontent.com/3969818/161876838-3a76b451-89b0-4055-8939-ad2c83db7062.png)

**Comment by kiwidude68** [comment]
@atscott Thanks for your comments re ngcc. Unfortunately even with that option checked the extension still has issues. I did see this error stack just now:
```
[Error - 1:58:31 PM] TypeError: Cannot read properties of undefined (reading 'startRecordingFilesWithChangedResolutions')
    at ConfiguredProject.Project.updateGraph (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:166985:38)
    at ConfiguredProject.updateGraph (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:168021:63)
    at updateProjectIfDirty (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:168510:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:170882:41)
    at ProjectService.openClientFileWithNormalizedPath (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:170989:31)
    at ProjectService.openClientFile (d:\Git\myproject\node_modules\typescript\lib\tsserverlibrary.js:170728:29)
    at Session.onDidOpenTextDocument (c:\Users\xxx\.vscode\extensions\angular.ng-template-14.0.0-next.0\server\index.js:4153:46)
    at c:\Users\xxx\.vscode\extensions\angular.ng-template-14.0.0-next.0\server\index.js:3795:48
    at handleNotification (c:\Users\xxx\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\vscode-jsonrpc\lib\common\connection.js:547:25)
```

**Comment by atscott** [comment]
@Proantagonist Thanks. I think I have enough information to perform further investigations for solution style/Nx projects. 

@kiwidude68 Unfortunately without a way to reproduce this, I can't guarantee any fix will address the problem for you. The only other time I've seen that error was in https://github.com/angular/vscode-ng-language-service/issues/1438, which should have been addressed. 

I've re-opened https://github.com/angular/vscode-ng-language-service/issues/876. After more investigation, I think there's more that should be done in this area.

**Comment by atscott** [comment]
This should be resolved in the 13.3.3 release.
